### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [nwtgck/piping-server#1010]
I dont know how to word it exactly, but can i host a file for any amount of users to download? Like for example do:

```
 cat file.tgz | curl -T - https://example.com/secret
 ```
 
 and the connection wont end after the first download from a receiver, the sender will stay connected and can send to unlimited recipients?

**Comment by nwtgck** [comment]
Piping Server is designed to improve security by not storing data on the server. This prevents unlimited recipients.

**Comment by dillfrescott** [comment]
Okay. I will close this then. Thank you
