### ISSUE TITLE
Browser SSH with keypair

### ISSUE THREAD

**Issue by healzer** [nwtgck/piping-server#432]
I found this repo on dev.to and it's amazing what you've created.
In particular the browser SSH capability, I'm wondering if it's possible to use a key pair mechanism as well, and not just user:pass ?

**Comment by nwtgck** [comment]
@healzer 
Thanks! https://github.com/nwtgck/piping-ssh-web is the right place for this issue because Piping Server is the core of data transfer, which does not care the data through itself. Feel free to open the issue in the repo.
