### ISSUE TITLE
Replace `url.resolve` and `url.parse` which were deprecated since v11.0.0 with the WHATWG URL API

### ISSUE THREAD

**Issue by matamatanot** [nwtgck/piping-server#440]
https://github.com/nwtgck/piping-server/blob/6b58205390e7954904954ed1ad49dcb77619491f/src/piping.ts#L105-L107
https://github.com/nwtgck/piping-server/blob/6b58205390e7954904954ed1ad49dcb77619491f/src/piping.ts#L83
[url.resolve](https://nodejs.org/api/url.html#url_url_resolve_from_to) and [url.parse](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) were **deprecated since v11.0.0**. Instead of above apis, the WHATWG URL API should be used. This API was introduced **since v7**, therefore it can be introduced.

At the end of April 2021, Node.js 10 will be [end-of-life](https://github.com/nodejs/Release).
You should probably migrate to the new API before you discontinue support for Node 10.

**Comment by nwtgck** [comment]
Thank you very much! We have to migrate the new API.

**Comment by nwtgck** [comment]
I fixed this issue on #442. Let me know if it has any mistake.
