### ISSUE TITLE
Screensharing firefox “text/plain” is not supported. 

### ISSUE THREAD

**Issue by flix444** [nwtgck/piping-server#472]
At first - nice application! 

I try to screen share like the article below explained, but i get an error message in Firefox.

https://dev.to/nwtgck/the-power-of-pure-http-screen-share-real-time-messaging-ssh-and-vnc-5ghc

`HTTP “Content-Type” of “text/plain” is not supported. Load of media resource http://****:8181/meintest2 failed.`

Using this HTML code: 
`
<meta charset="UTF-8">
<video src="http://*********:8181/meintest2" autoplay muted></video>
`
Have someone an idea?

**Comment by nwtgck** [comment]
The screen share on that post is only for latest Chrome now. fetch() streaming upload is supported only on latest Chrome.
ref: [Streaming requests with the fetch API https://web.dev/fetch-upload-streaming/]
