### ISSUE TITLE
command line "http basic auth" support

### ISSUE THREAD

**Issue by m2acgi** [nwtgck/piping-server#697]
Please add http basic auth to piping-server command line. 

The lastest version of piping-server must use with nginx or caddy to enable http basic auth. 

Thanks.

**Comment by nwtgck** [comment]
I've been considering design of basic auth. 

My short answer for now is [Rich Piping Server](https://github.com/nwtgck/rich-piping-server) for basic auth. The experimentation of basic auth or other auths will be conducted on the rich version. I'm planing to integrate [jwt-piping-server](https://github.com/nwtgck/jwt-piping-server) to the rich version.

**Comment by m2acgi** [comment]
Thanks.
