### ISSUE TITLE
[ERROR] The number of receivers has reached limits

### ISSUE THREAD

**Issue by m2acgi** [nwtgck/piping-server#830]
An error occurred in my long-running script, what could be the cause? 

Script look like this:

```bash
# ...

while true; do
    # ...
    curl --silent --max-time 3600 "${piping_server}/${piping_path}"
    # ...
    sleep 1
    # ...
done

# ...
```

**Comment by m2acgi** [comment]
Sorry, the problem has been resolved, thanks.

**Comment by ParkerOu** [comment]
@m2acgi 
How could I solve this issue? I'm encountering the same issue.

(Edited) Please disregard this message. I found the issue.
